#!/usr/bin/env python3
"""
gen_cell_models.py — 从 ISPD2012 contest.lib 生成 Verilog 行为模型
用于 VCS 仿真（无需商用 cell 库 Verilog 模型）

用法:
    python gen_cell_models.py --lib <contest.lib> --output <contest_cells.v>

原理:
    解析 Liberty (.lib) 中每个 cell 的 pin/function/ff 定义,
    生成等效 Verilog 行为模块, 支持组合逻辑 + D 触发器.

ISPD2012 contest.lib 包含 12 种基础 cell (331 个含不同驱动强度变体):
    组合: in01(INV), na02-04(NAND), no02-04(NOR),
          ao12/ao22(AND-OR-INV), oa12/oa22(OR-AND-INV)
    时序: ms00f80(DFF, d→ck→o)
"""

import re
import argparse
from pathlib import Path


def parse_lib(lib_path: str) -> list[dict]:
    """解析 .lib 文件, 提取每个 cell 的名称、引脚和功能."""
    text = Path(lib_path).read_text(encoding="utf-8", errors="replace")

    cells = []
    # 匹配 cell ("name") { ... } — 非贪婪, 按 cell 分割
    cell_blocks = re.split(r'(?=\n  cell \(")', text)

    for block in cell_blocks:
        m = re.match(r'\s*cell \("(\w+)"\)', block)
        if not m:
            continue
        cell_name = m.group(1)

        cell_info = {"name": cell_name, "pins": [], "ff": None}

        # 检测 FF
        ff_match = re.search(
            r'ff\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*\{'
            r'\s*next_state\s*:\s*"(\w+)"\s*;'
            r'\s*clocked_on\s*:\s*"(\w+)"\s*;',
            block,
        )
        if ff_match:
            cell_info["ff"] = {
                "state": ff_match.group(1),
                "state_n": ff_match.group(2),
                "next_state": ff_match.group(3),
                "clock": ff_match.group(4),
            }

        # 提取 pin
        pin_blocks = re.finditer(
            r'pin \("(\w+)"\)\s*\{(.*?)\n    \}', block, re.DOTALL
        )
        for pb in pin_blocks:
            pin_name = pb.group(1)
            pin_body = pb.group(2)

            direction = "input"
            dm = re.search(r'direction\s*:\s*(\w+)', pin_body)
            if dm:
                direction = dm.group(1)

            function = None
            fm = re.search(r'function\s*:\s*"([^"]+)"', pin_body)
            if fm:
                function = fm.group(1)

            cell_info["pins"].append({
                "name": pin_name,
                "direction": direction,
                "function": function,
            })

        cells.append(cell_info)

    return cells


def liberty_to_verilog_expr(func: str) -> str:
    """将 Liberty 布尔表达式转换为 Verilog 表达式.
    Liberty: ! (NOT), & (AND), | (OR), + (OR in some contexts)
    但 ISPD2012 contest.lib 用的是: ! + & () 其中 + 表示 OR
    """
    # Liberty 中 + 和 | 都是 OR
    expr = func.replace("+", " | ").replace("&", " & ")
    # ! 前缀 → ~ (Verilog bitwise NOT)
    expr = expr.replace("!", "~")
    return expr


def generate_verilog(cells: list[dict]) -> str:
    """为所有 cell 生成 Verilog 行为模型."""
    lines = []
    lines.append("// Auto-generated Verilog behavioral models for ISPD2012 contest.lib")
    lines.append("// Generated by gen_cell_models.py")
    lines.append("`timescale 1ps/1ps\n")

    # 去重: 同一 base cell 的不同驱动强度变体功能完全相同
    seen = set()

    for cell in cells:
        if cell["name"] in seen:
            continue
        seen.add(cell["name"])

        inputs = [p for p in cell["pins"] if p["direction"] == "input"]
        outputs = [p for p in cell["pins"] if p["direction"] == "output"]

        if not outputs:
            continue

        input_names = [p["name"] for p in inputs]
        output_names = [p["name"] for p in outputs]
        all_ports = input_names + output_names

        lines.append(f'module {cell["name"]} ({", ".join(all_ports)});')
        for p in inputs:
            lines.append(f"  input {p['name']};")
        for p in outputs:
            lines.append(f"  output {p['name']};")

        if cell["ff"]:
            # D flip-flop
            ff = cell["ff"]
            clk = ff["clock"]
            d = ff["next_state"]
            out_pin = outputs[0]["name"]
            lines.append(f"  reg {out_pin};")
            lines.append(f"  always @(posedge {clk})")
            lines.append(f"    {out_pin} <= {d};")
        else:
            # Combinational
            for p in outputs:
                if p["function"]:
                    expr = liberty_to_verilog_expr(p["function"])
                    # 如果 function 引用 ff state (iq), 跳过
                    if "iq" not in expr:
                        lines.append(f"  assign {p['name']} = {expr};")

        lines.append("endmodule\n")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="从 contest.lib 生成 Verilog 行为模型"
    )
    parser.add_argument("--lib", required=True, help="contest.lib 路径")
    parser.add_argument("--output", required=True, help="输出 .v 文件路径")
    args = parser.parse_args()

    cells = parse_lib(args.lib)
    verilog = generate_verilog(cells)
    Path(args.output).write_text(verilog, encoding="utf-8")
    print(f"已生成 {len(cells)} 个 cell 模型 → {args.output}")


if __name__ == "__main__":
    main()
