#!/usr/bin/env python3
"""
gen_testbench.py — 从 ISPD2012 门级网表自动生成随机激励 testbench

用法:
    python gen_testbench.py \
        --netlist <circuit.v> \
        --sdc <circuit.sdc> \
        --output <tb_circuit.v> \
        [--num-vectors 200] \
        [--vcd-file sim.vcd]

原理:
    1. 解析网表提取顶层模块名和所有 input/output 端口
    2. 解析 SDC 提取时钟端口名和周期
    3. 生成 testbench:
       - 时钟驱动 (从 SDC 获取周期)
       - 随机输入激励 (每个时钟周期随机翻转部分输入)
       - VCD dump ($dumpfile / $dumpvars)
       - 仿真结束后 $finish

ISPD2012 特点:
    - 所有电路的时钟端口名为 ispd_clk
    - 所有端口为 1-bit (no busses)
    - 时钟周期单位为 ps (从 SDC 读取)
"""

import re
import argparse
from pathlib import Path


def parse_netlist_ports(netlist_path: str) -> dict:
    """解析 Verilog 网表, 提取模块名和端口列表."""
    text = Path(netlist_path).read_text(encoding="utf-8", errors="replace")

    # 提取模块名
    mod_match = re.search(r'module\s+(\w+)\s*\(', text)
    if not mod_match:
        raise ValueError(f"无法在 {netlist_path} 中找到 module 声明")
    module_name = mod_match.group(1)

    # 提取 input/output 声明 (ISPD2012 全部是 1-bit, 无 bus)
    # 允许行首有空格缩进
    inputs = re.findall(r'^\s*input\s+(\w+)\s*;', text, re.MULTILINE)
    outputs = re.findall(r'^\s*output\s+(\w+)\s*;', text, re.MULTILINE)

    return {
        "module": module_name,
        "inputs": inputs,
        "outputs": outputs,
    }


def parse_sdc_clock(sdc_path: str) -> dict:
    """解析 SDC 文件, 提取时钟端口名和周期 (ps)."""
    text = Path(sdc_path).read_text(encoding="utf-8", errors="replace")

    clk_match = re.search(
        r'create_clock\s+.*?-period\s+([\d.]+)\s+.*?get_ports\s+(\w+)',
        text,
    )
    if not clk_match:
        raise ValueError(f"无法在 {sdc_path} 中找到 create_clock")

    period_ps = float(clk_match.group(1))
    clk_port = clk_match.group(2)
    return {"port": clk_port, "period_ps": period_ps}


def generate_testbench(
    module_name: str,
    inputs: list[str],
    outputs: list[str],
    clk_port: str,
    clk_period_ps: float,
    num_vectors: int,
    vcd_file: str,
    timescale_ps: int = 1,
) -> str:
    """生成 Verilog testbench 代码."""
    # 所有延时值需要除以 timescale 换算为 tick 数
    ts = timescale_ps
    half_period = clk_period_ps / 2

    # 将 clk 从普通 input 中分离
    data_inputs = [p for p in inputs if p != clk_port]

    lines = []
    lines.append(f"// Auto-generated testbench for {module_name}")
    lines.append(f"// Clock: {clk_port}, Period: {clk_period_ps} ps")
    lines.append(f"// Data inputs: {len(data_inputs)}, Outputs: {len(outputs)}")
    lines.append(f"// Test vectors: {num_vectors}")
    lines.append("// Generated by gen_testbench.py")
    lines.append("")
    lines.append(f"`timescale {ts}ps/{ts}ps")
    lines.append("")
    lines.append("module tb;")
    lines.append("")

    # 声明时钟
    lines.append(f"  reg {clk_port};")

    # 声明 data inputs 为 reg
    # 分批声明避免行太长
    batch_size = 10
    for i in range(0, len(data_inputs), batch_size):
        batch = data_inputs[i : i + batch_size]
        lines.append(f"  reg {', '.join(batch)};")

    lines.append("")

    # 声明 outputs 为 wire
    for i in range(0, len(outputs), batch_size):
        batch = outputs[i : i + batch_size]
        lines.append(f"  wire {', '.join(batch)};")

    lines.append("")

    # 随机种子和循环变量
    lines.append("  integer i;")
    lines.append("  integer seed;")
    lines.append("")

    # 时钟生成
    half_ticks = half_period / ts
    lines.append(f"  // Clock: period = {clk_period_ps} ps ({clk_period_ps/ts:.0f} ticks)")
    lines.append(f"  always #{half_ticks:.0f} {clk_port} = ~{clk_port};")
    lines.append("")

    # Initial block
    lines.append("  initial begin")
    lines.append(f'    $dumpfile("{vcd_file}");')
    lines.append("    $dumpvars(0, tb);")
    lines.append("")
    lines.append("    // Initialize")
    lines.append(f"    {clk_port} = 0;")
    lines.append("    seed = 42;")

    # 初始化所有 data inputs 为 0
    for i in range(0, len(data_inputs), batch_size):
        batch = data_inputs[i : i + batch_size]
        for p in batch:
            lines.append(f"    {p} = 0;")

    lines.append("")
    lines.append("    // Wait for reset settling")
    lines.append(f"    #{clk_period_ps * 5 / ts:.0f};")
    lines.append("")
    lines.append(f"    // Apply {num_vectors} random vectors")
    lines.append(f"    for (i = 0; i < {num_vectors}; i = i + 1) begin")
    lines.append(f"      @(posedge {clk_port});")

    # 随机翻转输入: 用 $random 逐个驱动
    # 对于大量端口, 分组赋值以减少仿真事件
    if len(data_inputs) <= 64:
        # 端口少: 逐个 $random
        for p in data_inputs:
            lines.append(f"      {p} = $random(seed);")
    else:
        # 端口多: 用分组策略, 每次只翻转约 25% 的端口
        lines.append("      // 每周期随机翻转约 25% 的输入端口")
        for idx, p in enumerate(data_inputs):
            # 用 idx 做模运算, 让不同端口在不同周期翻转
            group = idx % 4
            lines.append(
                f"      if ((i + {group}) % 4 == 0) {p} = $random(seed);"
            )

    lines.append("    end")
    lines.append("")
    lines.append("    // Let outputs settle")
    lines.append(f"    #{clk_period_ps * 10 / ts:.0f};")
    lines.append("")
    lines.append('    $display("Simulation finished: %0d vectors applied.", i);')
    lines.append("    $finish;")
    lines.append("  end")
    lines.append("")

    # DUT 实例化
    lines.append(f"  // DUT instantiation")
    lines.append(f"  {module_name} u0 (")
    all_ports = inputs + outputs
    for idx, p in enumerate(all_ports):
        comma = "," if idx < len(all_ports) - 1 else ""
        lines.append(f"    .{p}({p}){comma}")
    lines.append("  );")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="从 ISPD2012 门级网表生成随机激励 testbench"
    )
    parser.add_argument("--netlist", required=True, help="门级网表 .v 文件")
    parser.add_argument("--sdc", required=True, help="SDC 约束文件")
    parser.add_argument("--output", required=True, help="输出 testbench .v 文件")
    parser.add_argument(
        "--num-vectors", type=int, default=200,
        help="随机测试向量数 (默认 200)",
    )
    parser.add_argument(
        "--vcd-file", default="sim.vcd",
        help="VCD 输出文件名 (默认 sim.vcd)",
    )
    parser.add_argument(
        "--timescale-ps", type=int, default=1,
        help="timescale (ps), 默认 1; 设 10 则与 des_demo 一致",
    )
    args = parser.parse_args()

    # 解析网表
    ports = parse_netlist_ports(args.netlist)
    print(
        f"模块: {ports['module']}, "
        f"inputs: {len(ports['inputs'])}, "
        f"outputs: {len(ports['outputs'])}"
    )

    # 解析 SDC
    clk = parse_sdc_clock(args.sdc)
    print(f"时钟: {clk['port']}, 周期: {clk['period_ps']} ps")

    # 生成 testbench
    tb = generate_testbench(
        module_name=ports["module"],
        inputs=ports["inputs"],
        outputs=ports["outputs"],
        clk_port=clk["port"],
        clk_period_ps=clk["period_ps"],
        num_vectors=args.num_vectors,
        vcd_file=args.vcd_file,
        timescale_ps=args.timescale_ps,
    )

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(tb, encoding="utf-8")
    print(f"Testbench 已生成 → {args.output}")


if __name__ == "__main__":
    main()
