#
# Voltus Scheduler command file generated by voltus_rail on Tue Mar 17 13:55:18 2026
#
setvar log_file ./work/voltus_extractor.log
extracted_nets VSS VDD 
setvar output_cache_directory_name /tmp/innovus_temp_65366_IC_IC_3lzmeZ/zx_tmp_IC_66992
setvar library_name ./des3_pg_v15/techonly.cl
setvar output_directory_name ./work
setvar output_file_name TopLevelPGDB
setvar output_multi_pgdb true
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_65366_IC_IC_3lzmeZ/eps_out_65366.def.gz 
setvar exec_token "/tmp/innovus_temp_65366_IC_IC_3lzmeZ/eps_out_65366.def.gz"
setvar extraction_mode early
setvar zx_multinet_extraction false
extraction_type all none
extraction_type pattern VSS decoupled_rc
hierarchical_path_tracer netinst_table ./work/VSS.netinst
hierarchical_path_tracer cell_table ./work/VSS.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port # 0.0000 0.0000 Placement
label port # 0.0000 0.0000 Python
label port # 0.0000 0.0000 X(um)
label port pad_vss_0 2.3040 1.2160 M6
label port pad_vss_1 2.3040 201.2160 M6
label port pad_vss_2 382.9680 1.2160 M6
label port pad_vss_3 382.9680 201.2160 M6
label port pad_vss_4 1.2160 2.3040 M7
label port pad_vss_5 201.2160 2.3040 M7
label port pad_vss_6 1.2160 382.9680 M7
label port pad_vss_7 201.2160 382.9680 M7
extraction_type pattern VDD decoupled_rc
hierarchical_path_tracer netinst_table ./work/VDD.netinst
hierarchical_path_tracer cell_table ./work/VDD.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port # 0.0000 0.0000 Placement
label port # 0.0000 0.0000 Python
label port # 0.0000 0.0000 X(um)
label port pad_vdd_0 4.8640 3.7760 M6
label port pad_vdd_1 4.8640 203.7760 M6
label port pad_vdd_2 380.4080 3.7760 M6
label port pad_vdd_3 380.4080 203.7760 M6
label port pad_vdd_4 3.7760 4.8640 M7
label port pad_vdd_5 203.7760 4.8640 M7
label port pad_vdd_6 3.7760 380.4080 M7
label port pad_vdd_7 203.7760 380.4080 M7
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 4
setvar density_check_method database
setvar sfedb_path ./work/SFEDB 
setvar keep_log_file false
